# Generated by Django 5.0 on 2025-03-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cart_order_product_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Home_Decor', 'دکوراسیون منزل'), ('Jewelry', 'زیورآلات'), ('Gifts', 'هدیه'), ('Other', 'سایر')], default='loafer', max_length=10),
        ),
    ]
